language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - ./vendor/phpunit/phpunit/phpunit -c phpunit.xml

after_success:
  - test -z $COVERALLS || (composer require satooshi/php-coveralls && vendor/bin/coveralls -v)
